classDiagram
    class Bus {
        +string ID
        +double BatteryCapacity
        +double CurrentCharge
        +double kmPerKwh
        +string Location
        +double AverageSpeed
        +GetBatteryStatus() void
        +FilterBatteryStatus() void
        +GetBusStatus() void
        +GetBatteryTimeLeft() void
        +GetChargingTimeLeft() void

    }

    class Garage {
        +List<Bus> Busses
        +enum BusStatus
        +GetAllBuses() List<Bus>
        +GetBatteryStatus() void
        +FilterBatteryStatus() void
        +GetBusStatus() void
        +GetBatteryTimeLeft() void
        +GetChargingTimeLeft() void
        +SortByCurrentCharge() void
    }

    class BusStatus{
        <<enumeration>>
        InRoute
        Free
        Garage
        Charging
        Repair
    }
    
    Garage "1" --> "*" Bus
    Bus -- BusStatus : has a