sequenceDiagram
    participant Driftsmedarbejder
    participant System

    Driftsmedarbejder->>System: Valg Bus Liste
    System-->>Driftsmedarbejder: Bus Liste

    Driftsmedarbejder->>System: Valg Bus i Drift
    System-->>Driftsmedarbejder: Liste Bus i Drift
    
    Driftsmedarbejder->>System: Sorter efter Batteri Procent
    System-->>Driftsmedarbejder: Sorteret Liste