classDiagram
	class Bus {
		+string BusID	
	}

	class Garage {		
		+string ShiftPlanID	
		+List<Garage>ShiftPlanList
		+UpdateShiftPlan() : void
		+GetShiftPlanStatus() : void
	}

	Garage "1" --> "*" Bus