classDiagram
    class ShiftPlan{
		Shiftplan
	}
    class Bus {
        ID

    }
    class Garage {
        List Busses
        List ShiftPlans
    }
    Garage "1" --> "*" Bus
    Bus "1" --> "*" ShiftPlan
