sequenceDiagram
    participant Driftsmedarbejder
    participant System

    Driftsmedarbejder->>System: Valg Vagtplan til indlæsning
    System-->>Driftsmedarbejder: Vagtplan er indlæst

    Driftsmedarbejder->>System: ValgBatteriStatus
    System-->>Driftsmedarbejder: BatteriStatus
    
    Driftsmedarbejder->>System: FilterLavBatteriStatus
    System-->>Driftsmedarbejder: BusListeLaveBatteriStatus

    Driftsmedarbejder->>System: Valg BusID
    System-->>Driftsmedarbejder: Detaljeret Bus Status

    Driftsmedarbejder->>System: Valg Estimeret Driftstid
    System-->>Driftsmedarbejder: Estimeret Driftstid
