classDiagram
    class Bus {
        +string ID
        +double Batterikapacity
        +double Usage
        +Update(Batterikapacity, Usage)
    }

    class Garage {
        +List<Bus> Busses
        +AddBus(Bus bus)
        +EditBus(string id, double newCapacity, double newConsumption)
        +RemoveBus(string id)
        +GetAllBuses() List<Bus>
    }
    
    Garage --> Bus
