classDiagram
    class Bus {
        +string ID
        +double BatteriCapacity
        +double Usage
        +Update(Batterikapacity, Usage)
    }

    class Garage {
        +List<Bus> Busses
        +AddBus(Bus bus)
        +EditBus(string id, double newBatteryCapacity, double newBettertyUsage)
        +RemoveBus(string id)
        +GetAllBuses() List<Bus>
    }
    
    Garage "1" --> "*" Bus
