flowchart TD
    A[Administrer Busser] --> B[Opret ny Bus]
    A --> C[Se liste over Busser]
    A --> D[Rediger valgt Bus]
    A --> E[Slet valgt Bus]

    F[Adminstrer Busser] --> G[Opret ny Bus]
    F --> H[Se liste over Busser]
    H --> I[Rediger Valgt Bus]
    H --> J[Slet valgt Bus]